CREATE TABLE pilota(
Foto blob() NOT NULL,
Nome VARCHAR(45) NOT NULL,
Cognome VARCHAR(45) NOT NULL,
DataDiNascita DATE NOT NULL,
LuogoDiNascita VARCHAR(45) NOT NULL,
Nazionalità VARCHAR(45) NOT NULL,
Scuderia VARCHAR(45) NOT NULL,
Numero INT NOT NULL,
TitoliMondiali INT NOT NULL,
Monoposto VARCHAR(45) NOT NULL,
ProfiloSocial VARCHAR(45) NOT NULL,
Biografia VARCHAR(45) NOT NULL
);

CREATE TABLE Scuderia(
Foto blob() NOT NULL,
Nome VARCHAR(45) NOT NULL,
AnnoEsordio INT NOT NULL,
Nazionalità VARCHAR(45) NOT NULL,
NumeroVittorie INT NOT NULL,
PrimoPilota VARCHAR(45) NOT NULL,
SecondoPilota VARCHAR(45) NOT NULL,
TeamPrincipal VARCHAR(45) NOT NULL,
SitoWeb VARCHAR(45) NOT NULL,
Storia VARCHAR(45) NOT NULL
);

CREATE TABLE Circuito(
Nome VARCHAR(45) NOT NULL,
Lunghezza INT NOT NULL,
Città VARCHAR(45) NOT NULL,
Nazione VARCHAR(45) NOT NULL,
NumeroGiri INT NOT NULL,
UltimoVincitore VARCHAR(45) NOT NULL,
MigliorTempo TIME() NOT NULL,
PilotaMigliorTempo VARCHAR(45) NOT NULL
);

CREATE TABLE Monoposto(
Nome VARCHAR(45) NOT NULL,
Motore VARCHAR(45) NOT NULL,
NumeroVittorie INT NOT NULL,
AnnoProduzione INT NOT NULL);

CREATE TABLE Gare(
ListaPiloti VARCHAR(45) NOT NULL,
ClassificaGara VARCHAR(45) NOT NULL,
Data DATE NOT NULL,
GrigliaDiPartenza VARCHAR(45) NOT NULL);

CREATE TABLE ClassificaPiloti(
NomePilota VARCHAR(45) NOT NULL,
Posizione INT NOT NULL,
Punti INT NOT NULL,
Anno INT NOT NULL
);

CREATE TABLE ClassificaCostruttori(
NomeScuderia VARCHAR(45) NOT NULL,
Posizione INT NOT NULL,
Punti INT NOT NULL,
Anno INT NOT NULL
);